# Generated by Django 3.2.2 on 2021-05-08 05:14

from django.conf import settings
from django.db import migrations, models
from django.db.models.signals import post_migrate
import django.db.models.deletion
import uuid


def insert_initial_catalogs_data(apps):
    SectionType = apps.get_model("SectionType")
    ElementType = apps.get_model("ElementType")

    work_history = SectionType(name="Work History", code="work_history")
    work_history.save()
    skills = SectionType(name="Skills", code="skills")
    skills.save()
    contact_info = SectionType(name="Contact", code="contact_info")
    contact_info.save()

    work = ElementType(name="Work History", code="work")
    work.save()
    skill = ElementType(name="", code="skill")
    skill.save()
    contact = ElementType(name="Contact", code="contact")
    contact.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=128)),
                ("subtitle", models.CharField(max_length=128)),
                ("description", models.TextField()),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ElementType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=36)),
                ("enabled", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SectionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=36)),
                ("enabled", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=128)),
                ("order", models.IntegerField()),
                ("icon_url", models.URLField()),
                (
                    "curriculum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structure.curriculum",
                    ),
                ),
                (
                    "section_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structure.sectiontype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=128)),
                ("subtitle", models.CharField(blank=True, max_length=128, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(blank=True, null=True)),
                ("level", models.IntegerField(blank=True, null=True)),
                ("date_display_start", models.DateTimeField(blank=True, null=True)),
                ("date_display_end", models.DateTimeField(blank=True, null=True)),
                (
                    "element_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structure.elementtype",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="structure.section",
                    ),
                ),
            ],
        ),
    ]

    def ready(self):
        post_migrate.connect(insert_initial_catalogs_data, sender=self)
